spring:
  application:
    name: authentication-service
  datasource:
    url: jdbc:postgresql://localhost:5433/users_database
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password
    hikari:
      maximumPoolSize: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: ${SERVER_PORT:8083}

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

jwt:
  secret: KXiUPknkoVDCHdNrrYnxmA5oQLbv+LE7eHG8vkk71fjEPq0lmlZKwBhUVLUqKSmGam8P4kWxXKTGCDRgpZ5BMA==

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR
